import React from 'react';
import { motion } from 'framer-motion';
import {
    Target, Lightbulb, PenTool, Search,
    BookOpen, MessageSquare, Zap, Gift,
    User, Mail, Layout, Terminal
} from 'lucide-react';

const mainTools = [
    {
        icon: <Target className="w-5 h-5" />,
        color: "bg-blue-600",
        title: "Informational Ebook Subniche Ideas Creator",
        desc: "Dive deep into your niche with our Informational Ebook Subniche Ideas tool. It helps you find specific areas that aren't as crowded, giving your ebook a better chance to shine and attract a dedicated audience."
    },
    {
        icon: <Lightbulb className="w-5 h-5" />,
        color: "bg-purple-600",
        title: "Novel Ideas Generator",
        desc: "Stuck on what your next big novel should be about? Our Novel Ideas tool throws exciting suggestions your way, sparking your creativity and helping you start your storytelling journey with a bang."
    },
    {
        icon: <PenTool className="w-5 h-5" />,
        color: "bg-emerald-600",
        title: "Novel Title Ideas Creator",
        desc: "Find the perfect catchy title for your novel with our Novel Title Ideas tool. It's all about grabbing attention and making sure your book stands out from the rest right from the get-go."
    },
    {
        icon: <Search className="w-5 h-5" />,
        color: "bg-orange-600",
        title: "Informational Ebook Niche Ideas",
        desc: "Not sure which niche to tackle in your next ebook? Our Informational Ebook Niche Ideas tool offers fresh insights into profitable niches that cater to your interests and market demand."
    },
    {
        icon: <BookOpen className="w-5 h-5" />,
        color: "bg-teal-600",
        title: "Informational Ebook Title Ideas",
        desc: "Get your ebook noticed with a title that piques curiosity. Our Informational Ebook Title Ideas tool helps you craft compelling titles that draw readers in from the very first glance."
    },
    {
        icon: <MessageSquare className="w-5 h-5" />,
        color: "bg-indigo-600",
        title: "Book Summary (Amazon KDP)",
        desc: "Catch readers' eyes with a killer book summary. Our Book Summary tool for Amazon KDP crafts concise, enticing summaries that give potential readers a tantalizing glimpse into your book."
    },
    {
        icon: <Search className="w-5 h-5" />,
        color: "bg-yellow-600",
        title: "Keyword Research for Amazon KDP",
        desc: "Optimize your Amazon listings with our Keyword Research tool for Amazon KDP. It helps you discover the keywords that potential readers are using, boosting your book's visibility and sales."
    },
    {
        icon: <BookOpen className="w-5 h-5" />,
        color: "bg-pink-600",
        title: "Novel Outline Creator",
        desc: "Turn that novel idea into a structured masterpiece. Our Novel Outline tool guides you through the process of building a coherent and captivating story framework step by step."
    },
    {
        icon: <Zap className="w-5 h-5" />,
        color: "bg-blue-500",
        title: "AI Short Story Generator",
        desc: "Spark the imagination of young readers. Our Short Story Creator for children helps you come up with fun, engaging stories that entertain and educate kids."
    },
    {
        icon: <PenTool className="w-5 h-5" />,
        color: "bg-emerald-500",
        title: "AI Short Poem Generator",
        desc: "Delight little ones with rhythmic magic. Our Short Poem Creator for children guides you in crafting short, catchy poems that are perfect for early readers."
    },
    {
        icon: <Target className="w-5 h-5" />,
        color: "bg-purple-500",
        title: "AI Course Name Generator",
        desc: "Captivate potential students right away with intriguing course titles generated by our Course Title Ideas tool. It's all about making a great first impression."
    },
    {
        icon: <Gift className="w-5 h-5" />,
        color: "bg-orange-500",
        title: "AI Marketing Strategy Generator",
        desc: "Plan your path to success with our Marketing Strategy tool. It guides you through creating a comprehensive strategy that aligns with your business goals and market needs."
    }
];

const secondaryTools = [
    { icon: <User className="w-5 h-5" />, title: "Author Bio Generator", color: "text-blue-600", bg: "bg-blue-50" },
    { icon: <Mail className="w-5 h-5" />, title: "AI Email Writer", color: "text-emerald-600", bg: "bg-emerald-50" },
    { icon: <Layout className="w-5 h-5" />, title: "AI Target Audience Problem Generator", color: "text-purple-600", bg: "bg-purple-50" },
    { icon: <Zap className="w-5 h-5" />, title: "AI Cold Email Writer", color: "text-orange-600", bg: "bg-orange-50" }
];

export const MarketingTools = () => {
    return (
        <section className="py-24 bg-white overflow-hidden">
            <div className="container mx-auto px-4">
                <div className="text-center mb-20">
                    <h2 className="text-4xl md:text-5xl font-black text-[#0f172a] mb-6">
                        Explore our eBook Creation & Marketing Tools
                    </h2>
                    <p className="text-slate-400 font-bold mb-10">
                        (Click on any to open the tool ↓)
                    </p>
                </div>

                {/* Main Tools Grid */}
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 max-w-7xl mx-auto mb-20 px-8">
                    {mainTools.map((tool, idx) => (
                        <motion.div
                            key={idx}
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            transition={{ delay: idx * 0.05 }}
                            viewport={{ once: true }}
                            className="bg-white rounded-3xl p-8 border border-slate-100 shadow-sm hover:shadow-xl transition-all duration-300 flex flex-col group cursor-pointer"
                        >
                            <div className={`w-10 h-10 rounded-xl ${tool.color} flex items-center justify-center text-white mb-6 shadow-lg shadow-gray-200 group-hover:scale-110 transition-transform`}>
                                {tool.icon}
                            </div>

                            <h4 className="text-[14px] font-black text-[#0f172a] mb-4 leading-tight group-hover:text-blue-600 transition-colors">
                                {tool.title}
                            </h4>

                            <p className="text-slate-400 text-[11px] leading-relaxed font-bold">
                                {tool.desc}
                            </p>
                        </motion.div>
                    ))}
                </div>

                {/* Secondary Tools Block */}
                <motion.div
                    initial={{ opacity: 0, y: 30 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    className="max-w-6xl mx-auto bg-white rounded-[2.5rem] p-12 border border-slate-100 shadow-md text-center"
                >
                    <h3 className="text-2xl font-black text-[#0f172a] mb-12">And Many More Tools Available!</h3>

                    <div className="grid grid-cols-2 md:grid-cols-4 gap-12 mb-16 px-4">
                        {secondaryTools.map((tool, idx) => (
                            <div key={idx} className="flex flex-col items-center gap-4 group">
                                <div className={`w-12 h-12 rounded-2xl ${tool.bg} ${tool.color} flex items-center justify-center group-hover:scale-110 transition-transform`}>
                                    {tool.icon}
                                </div>
                                <span className="text-[12px] font-black text-[#0f172a] max-w-[120px]">{tool.title}</span>
                            </div>
                        ))}
                    </div>

                    <p className="text-slate-400 text-xs font-bold">
                        Discover all our AI-powered tools designed to help you create, market, and sell your ebooks successfully.
                    </p>
                </motion.div>
            </div>
        </section>
    );
};
